use_frameworks!

target 'BlueShopping' do
     pod 'BMSPush'
     pod 'Presentr'
	 pod 'BMSAnalytics'
     pod 'OpenWhisk', :git => 'https://github.com/openwhisk/openwhisk-client-swift.git', :tag => '0.2.2'
     pod 'IBMMobileFirstPlatformFoundation'
end